//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market_Stok_Yönetimi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kasiyer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kasiyer()
        {
            this.Satis = new HashSet<Satis>();
        }
    
        public int KasiyerID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public int KasaID { get; set; }
    
        public virtual Kasa Kasa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satis> Satis { get; set; }
    }
}
