//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market_Stok_Yönetimi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satis
    {
        public int SatisID { get; set; }
        public int UrunID { get; set; }
        public int KasiyerID { get; set; }
        public int Miktar { get; set; }
        public decimal BirimFiyat { get; set; }
        public System.DateTime SatisTarihi { get; set; }
        public int KasaID { get; set; }
        public decimal ToplamTutar { get; set; }
    
        public virtual Kasa Kasa { get; set; }
        public virtual Kasiyer Kasiyer { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
